### ISSUE TITLE
Printing cutout

### ISSUE THREAD

**Issue by Zulex** [HL2-DINO/DINO-IR-Tools#1]
Hi,

First of all, thanks for all the great work! Impressive work.

I am trying to print the model right now, and I am not 100% sure which print orientation you were using. Especially the circular 'cap'/'cutout' is difficult to print as it has overhangs in both directions. Any particular reason the 'top' part is not flat? Any hints on this would be greatly appreciated.

**Comment by hiqb217** [comment]
Hi!

RE: the curved design at the top, I think I'd originally just wanted to create a gradual slope to the face of the IR tape.

For print orientation, this is how I'd printed out the stylus tool, so you could probably do something similar if you're printing out the 'outer' part of the marker assembly. Seemed to print out the least amount of support material this way as well. Hope that helps!

![image](https://github.com/user-attachments/assets/37c072e3-d5ff-4e75-945e-9f973b770a1b)
